### ISSUE TITLE
extra image

### ISSUE THREAD

**Issue by jenbrannstrom** [qualifiedleads/brainfree#1]
@KNLopez please can you add this image under the "services" tab
http://prntscr.com/iaj2en

It;s from here:
https://www.wix.com/website-template/view/html/1822?originUrl=https%3A%2F%2Fwww.wix.com%2Fwebsite%2Ftemplates%3Fcriteria%3Dchurch&bookName=&galleryDocIndex=2

**Comment by KNLopez** [comment]
done
