### ISSUE TITLE
Home page text

### ISSUE THREAD

**Issue by jenbrannstrom** [qualifiedleads/brainfree#2]
Please add the following text to the home page, beneath the main image:

> (H1) Worship Services

(body)Each Sunday, and sometimes on other days of the week as well, the Church’s Chaplain or another minister conducts a public worship service which is open to both members and non-members of the Church.

These services comprise a recitation of the Creed of Scientology, sermons, congregational auditing and prayer. As such they provide an occasion for everyone to commune with the Infinite and revitalize one spiritually.

> SUNDAY SERVICE

Scientology helps each being to regain awareness of himself or herself as an immortal spiritual being and the rehabilitation of full spiritual potential—to achieve a recognition of spiritual existence and one’s relationship to the Supreme Being. God is identified in Scientology as the Eighth Dynamic. All Scientology services bring people closer to the Eighth Dynamic, and the congregational services especially focus on this. It is a bringing together of many beings in a joint spiritual experience and an occasion to recognize the ultimate which is the Eighth Dynamic or God.

The Church of Scientology Sunday service consists of a reciting of the Creed of the Church, a sermon based on the writings of the Scientology Founder L. Ron Hubbard, congregational group auditing and prayer. There may also be music and singing, as well as announcements of Church events and programs.

The Creed of the Church of Scientology

Every Sunday service begins with the Creed of the Church of Scientology. The creed affirms the spiritual aims of the Church, outlines the Church’s social mission and affords members the opportunity to rededicate themselves to the religion.

The Sermon

The Sunday sermon typically addresses a topic related to an important Scientology principle or practice and explores its relevance to everyday existence. One of the minister’s goals is for each member of the congregation to leave the Church with a greater level of spiritual awareness and enlightenment and an increased understanding of how to apply the truths learned during the service to his or her life.

L. Ron Hubbard Lecture

Born in the 20th century, Scientology is unique among the major religions of the world in that all of its Scripture is faithful to original written and spoken words. These words have been preserved exactly as authored and spoken—and always will be—thanks to the technology available in this era, giving Scientologists the assurance that their religion will remain pure and free of alteration. Mr. Hubbard delivered more than 3,000 lectures to audiences around the world, detailing his discoveries and the research paths he traveled to make them. Some of these cover advanced concepts directed to the experienced Scientologist, but many address the fundamentals of the religion and are suitable for general audiences. Often one of these is selected and played at the Sunday service.

Group Auditing

Congregational group auditing is an integral part of every Sunday service. The minister acts as the auditor for the group, ministering auditing services particularly suited for groups and often aligned with the intended sermon of the day. Group auditing consists of an instruction or series of instructions which can increase one’s awareness and put one in better communication with everything and everyone about the person. Importantly they help the individual free himself of adverse material influences in the physical universe and become more able to regain his own spiritual awareness.

Announcements

As Scientologists are actively committed to the practice of their religion, including fulfilling Scientology’s goal of making this world a better place for all Mankind, many of those attending the Sunday service participate in community outreach and benevolent activities for which Scientology churches are renowned. Part of the minister’s duties, therefore, involves informing the congregation of on-going community programs or activities in which the Church is participating and engaging members of the congregation in how they may contribute to these activities.

Prayer

All Sunday Services include the Prayer for Total Freedom, which expresses what Scientology seeks to achieve and asks God to let this be so.

**Comment by KNLopez** [comment]
added
